# frozen_string_literal: true

source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.1.4'
gem 'rspec'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "github-pages", group: :jekyll_plugins
gem "jekyll", "~> 3.9"
